### ISSUE TITLE
Replay bot dead if you restart the timer immediately after finish the map

### ISSUE THREAD

**Issue by IrNep** [KZGlobalTeam/gokz#246] opened 2022-03-14 13:53 UTC

**Comment by Ferexx** [comment] 2022-03-14 22:28
I'm gonna need you to be more descriptive here, please.

**Comment by IrNep** [comment] 2022-03-15 02:03
> I'm gonna need you to be more descriptive here, please.

1. Finish a run.
2. Immediately use sm_restart.
3. Start the timer.
4. replay file destroyed.

**Comment by IrNep** [comment] 2022-03-15 02:31
https://streamable.com/9mzyo8

**Comment by Ferexx** [comment] 2022-03-15 15:14
Thanks for this. The video is very helpful. I've identified the cause of the problem and aim to have it fixed in the next release

**Comment by zealain** [comment] 2022-03-18 12:55
This should hopefully be fixed in 3.0.5, if not please re-open the issue.

**Closed by zealain** 2022-03-18 12:55 UTC
